# Feature selection and Modeling

It is nearly impossible to correctly label all observations or agents as corrupt. We decided then to characterize possibly corrupt cases by the suspicious behaviour of agents involved in the process, so we looked at two main dimensions:

## Missing Data

## Suspicious connections 
Our data modeling process implies creating a fairly complex multi layer graph, for which not all centrality measures can be computed. We combined graph structure measures with more intuitive variables to include in our analysis: 

### Weighted degree centrality of bureaucrat $i$, firm $j$ or RU $u$

Weighted degree centrality of some vertex $v$ is defined as follows: $C_{D}(v) := deg(v)$

### Concentration of bureaucrat connections

Inspired in the construction of Herfindahl Index, this variable is constructed as: $h_i &= \sum_j w_{i,j}^2$, where $w_{i,j}$ is weight of firm $j$ in the total value assigned through contracts by bureaucrat $i$. 

### Concentration of firm connections
This is intuitively seen as some probability that firm $j$ has at least one crony relationship. \bar{w_k} &= \underset{i}{max w_{i,k}}

### Distance to other agents
We also compute the shortest paths distance to a sanctioned firm, to a ghost firm or to a bureaucrat with $h_i>.6$